[package]
name = "processing_ffi"
version = "0.1.0"
edition = "2024"

[lib]
name = "processing"
crate-type = ["cdylib"]

[dependencies]
processing = { workspace = true }
bevy = { workspace = true }

[build-dependencies]
cbindgen = "0.29"
