[package]
name = "processing-ffi"
version = "0.1.0"
edition = "2024"

[lib]
name = "processing"
crate-type = ["cdylib"]

[dependencies]
renderer = { path = "../processing-render" }
bevy = { workspace = true }

[build-dependencies]
cbindgen = "0.29"
